version: "3.7"

services:
    db:
        image: postgres:14.1
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: user42
            POSTGRES_DB: transcendence
        volumes:
        - ./postgres-data:/var/lib/postgresql/data
        expose:
        - "5432"
        
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
        - "8080:8080"

    front:
        container_name: frontend
        build:
            context: ./front
            dockerfile: Dockerfile.front
        expose:
        - "3000"

    back:
        container_name: backend
        build:
            context: ./back
            dockerfile: Dockerfile.back
        depends_on:
        - "db"
        expose:
        - "4000"

    reverse-proxy:
        image: nginx:1.20.2
        container_name: nginx
        restart: always
        depends_on:
        - "front"
        - "back"
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
        - "80:80"