version: "3.7"

services:
    db:
        image: postgres:14.1
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: user42
            POSTGRES_DB: transcendence
        volumes:
        - ./postgres-data:/var/lib/postgresql/data
        ports:
        - "5432:5432"
        
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
        - "8080:8080"
    
    reverse-proxy:
        image: nginx:1.20.2
        container_name: nginx
        restart: always
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
        - "80:80"

    front:
        container_name: frontend
        build:
            context: ./front
            dockerfile: Dockerfile.front
        volumes:
        - ./front:/app
        ports:
        - "3000:3000"

    back:
        container_name: backend
        build:
            context: ./back
            dockerfile: Dockerfile.back
        volumes:
        - ./back:/app
        ports:
        - "4000:4000"